install:
	-ln -vs ${PWD}/.cheat               ${HOME}/.cheat
	-ln -vs ${PWD}/.vim                 ${HOME}/.vim
	-ln -vs ${PWD}/.ackrc               ${HOME}/.ackrc
	-ln -vs ${PWD}/.bash_profile        ${HOME}/.bash_profile
	-ln -vs ${PWD}/.bashrc              ${HOME}/.bashrc
	-ln -vs ${PWD}/.git-completion.bash ${HOME}/.git-completion.bash
	-ln -vs ${PWD}/.git-prompt.sh       ${HOME}/.git-prompt.sh
	-ln -vs ${PWD}/.gitconfig           ${HOME}/.gitconfig
	-ln -vs ${PWD}/.gitignore_global    ${HOME}/.gitignore_global
	-ln -vs ${PWD}/.profile             ${HOME}/.profile
	-ln -vs ${PWD}/.vimrc               ${HOME}/.vimrc
	-ln -vs ${PWD}/.zshrc               ${HOME}/.zshrc
